- name: Create document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ app_user }}"
    mode: '0755'

- name: Download and unarchive zip simple-lamp-app
  ansible.builtin.unarchive:
    src: "{{ download_app_link }}"
    dest: /var/www/
    remote_src: yes

- name: Set up Apache virtualhost
  template:
    src: "files/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
  notify: Reload Apache

- name: Set up config.php
  ansible.builtin.template:
    src: "files/config.php.j2"
    dest: "/var/www/{{ http_host }}/config.php"
    
- name: Enable new site
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache
    
- name: Restore database ignoring errors
  community.mysql.mysql_db:
    name: simple_lamp
    state: import
    target: /var/www/{{ http_host }}/simple_lamp.sql
    force: true

- name: Change directory ownership
  ansible.builtin.file:
    path: /var/www/{{ http_host }}/uploads
    owner: www-data
    group: www-data
